name: Docker Image CI

on:
  release:
    types: [published]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set realease tag
      id: tag-selector
      run: echo -n "TAG=" >> "$GITHUB_OUTPUT" && if [ ${{ github.event_name }} = 'release' ];then echo "${{ github.event.release.tag_name }}"; else date +%Y%m%d%H%M; fi >> "$GITHUB_OUTPUT"
    
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        username: svenkleinert
        password: ${{ secrets.DOCKERHUB_PAT }}
          
    - name: Build the Docker image
      env:
          TAG: ${{ steps.tag-selector.outputs.TAG }}
      run: docker build -t svenkleinert/pxd-ihs-zope:$TAG .

    - name: Push Docker image
      if: ${{ github.event_name != 'pull_request' }}
      run: docker push svenkleinertpxd-ihs-zope:$TAG
