name: Docker Image CI

on:
  release:
    types: [published]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set realease tag
      id: tag-selector
      run: echo -n "TAG=" >> "$GITHUB_OUTPUT" && if [ ${{ github.event_name }} = 'release' ];then echo "${{ github.event.release.tag_name }}"; else date +%Y%m%d%H%M; fi >> "$GITHUB_OUTPUT"
    
    - name: Log in to docker hub
      uses: docker/login-action@v3
      with:
        username: svenkleinert
        password: ${{ secrets.DOCKERHUB_PAT }}
          
    - name: Build the Docker image
      env:
        TAG: ${{ steps.tag-selector.outputs.TAG }}
      run: docker build -t svenkleinert/pxd-ihs-zope:$TAG .

    - name: Tag Docker image
      if: ${{ github.event_name == 'release' }}
      env:
        TAG: ${{ steps.tag-selector.outputs.TAG }}
      run: docker tag svenkleinert/pxd-ihs-zope:$TAG svenkleinert/pxd-ihs-zope:latest

    - name: Push Docker image
      env:
        TAG: ${{ steps.tag-selector.outputs.TAG }}
      run: docker push --all-tags svenkleinert/pxd-ihs-zope

    - name: Add comment to PR
      if: ${{ github.event_name == 'pull_request' }}
      env:
        TAG: ${{ steps.tag-selector.outputs.TAG }}
      uses: actions/github-script@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            issue_number: context.issue.number,
            repo: context.repo.repo,
            body: "image with tag '" + process.env.TAG + "' created, see https://hub.docker.com/repository/docker/svenkleinert/pxd-ihs-zope/tags/" + process.env.TAG + "/"
          })
